name: deploy docs

on: workflow_dispatch

jobs: 
  deploy:
    name: Deploy documentation

    runs-on: ubuntu-latest

    env:
      CI_AUTHOR: docsdeploybot

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install python dependencies
        run: poetry install --no-interaction

      - name: Run Mike deploy
        run: poetry run mike deploy -u

      - name: Push gh-pages branch
        run: |
          git checkout gh-pages
          git push
